---
# Per environment values which override defaults in hmpps-community-payback-supervisors-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: community-payback-supervisors-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-community-payback-supervisors-dev-cert

  env:
    INGRESS_URL: 'https://community-payback-supervisors-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    COMMUNITY_PAYBACK_API_URL: 'https://community-payback-api-dev.hmpps.service.justice.gov.uk'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: 'true'
    CLEAR_SESSION_STATUSES_ENABLED: 'true'

generic-prometheus-alerts:
  alertSeverity: hmpps-community-payback-nonprod
